config/routes.rb
Rails.application.routes.draw do
  scope :admin do
    resources :products
    resources :categories
  end

  get "products", to: "products#public_index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord

  # VALIDATIONS
  validates :name, presence: true, length: { minimum: 3 }

  # ASSOCIATIONS
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord

  # VALIDATIONS
  validates :name, presence: true, length: { minimum: 3 }
  validates :price, presence: true
  validates :price, numericality: { greater_than: 0 }
  validates :category_id, presence: true

  # ASSOCIATIONS
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  def public_index
    @categories = Category.all
  end
  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    if @category.save
      respond_to do |format|
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    if @category.update(category_params)
      respond_to do |format|
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
        format.turbo_stream
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
      format.turbo_stream
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all.includes(:category)
  end

  def public_index
    @products = Product.all.includes(:category)
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    if @product.save
      respond_to do |format|
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    if @product.update(product_params)
      respond_to do |format|
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
        format.turbo_stream
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
      format.turbo_stream
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price, :description, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_category.html.erb
<%= turbo_frame_tag category do %>
  <li class="list-group-item">
    <div class="row mt-2">

      <span class="col-md-2 col-sm-12">
        <strong><%= category.name %></strong>
      </span>

      <span class="col-md col-sm-12 mb-3">
        <%= category.description %>
      </span>

      <span class="col-auto mb-2">
        <%= link_to "Show", category, data: { turbo_frame: "_top" }, class: "btn btn-secondary" %>
        <%= link_to "Delete", category, class: "btn btn-danger", method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" } %>
        <%= link_to "Edit", edit_category_path(category), data: { turbo_frame: "modal" }, class: "btn btn-success" %>
      </span>

    </div>
  </li>
<% end %>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div>
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="mt-3">
    <%= form.button type: :submit, class: "btn btn-primary" %>
    <%= link_to "Cancel", categories_path, data: { turbo_frame: "_top" }, class: "btn btn-warning" %>
  </div>
<% end %>

app/views/categories/create.turbo_stream.erb
<%= turbo_stream.prepend "categories", @category %>

app/views/categories/destroy.turbo_stream.erb
<%= turbo_stream.remove @category %>

app/views/categories/edit.html.erb
<main class="container">
  <%= link_to "Back to categories", categories_path %>

  <%= turbo_frame_tag "modal" do %>
    <h1 class="display-6 ms-3 mt-2">
      Edit Category
    </h1>

    <div class="modal-body">
      <%= render "categories/form", category: @category %>
    </div>
  <% end %>
</main>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="row">
  <div class="col">
    <h1 class="display-6">Categories</h1>
  </div>
  <div class="col-auto">
    <%= link_to "New Category", new_category_path, class: "btn btn-primary", data: { turbo_frame: "modal" } %>
  </div>
</di>

<ul class="list-group mt-3">
  <%= turbo_frame_tag "categories" do %>
    <% if @categories.blank? %>
      <h1 class="display-6">Şu wagta çenli hiç Category girizilmedik...</h1>
    <% end %>
    <%= render @categories %>
  <% end %>
</ul>

app/views/categories/new.html.erb
<main class="container">
  <%= link_to "Back to categories", categories_path %>

  <%= turbo_frame_tag "modal" do %>
    <h1 class="display-6 ms-3 mt-2">
      New Category
    </h1>

    <div class="modal-body">
      <%= render "categories/form", category: @category %>
    </div>
  <% end %>
</main>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/categories/update.turbo_stream.erb
<%= turbo_stream.replace @category do %>
  <%= render @category %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Integround</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fa-solid fa-gear"></i> Menu
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "Categories", categories_path, class: "dropdown-item" %></li>
            <li><%= link_to "Products", products_path, class: "dropdown-item" %></li>
          </ul>
        </li>

      </ul>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Integround</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script>window.process = { env: {} }</script>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container mt-5">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
      <div 
        class="modal" 
        tabindex="-1"
        data-controller="modal"
        data-action="turbo:frame-load->modal#open turbo:submit-end->modal#close"
      >
        <div class="modal-dialog">
          <div class="modal-content">
            <%= turbo_frame_tag "modal" %>
          </div>
        </div>
      </div>

    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div>
    <%= form.label :category_id, class: "form-label" %>
    <%= form.collection_select :category_id, @categories, :id, :name, { include_blank: "No Category" }, { class: "form-select" } %>
  </div>

  <div>
    <%= form.label :price, class: "form-label" %>
    <%= form.text_field :price, class: "form-control" %>
  </div>

  <div>
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="mt-3">
    <%= form.button type: :submit, class: "btn btn-primary" %>
    <%= link_to "Cancel", products_path, data: { turbo_frame: "_top" }, class: "btn btn-warning"  %>
  </div>
<% end %>

app/views/products/_product.html.erb
<%= turbo_frame_tag product do %>
  <li class="list-group-item">
    <div class="row mt-2">

      <span class="col-md-2 col-sm-12">
        <%= product.name %>
      </span>

      <span class="col-md-2 col-sm-12">
        <%= product.category.name %>
      </span>

      <span class="col-md col-sm-12 mb-3">
        <%= product.description %>
      </span>

      <span class="col-auto mb-2">
        <%= link_to "Show", product, data: { turbo_frame: "_top" }, class: "btn btn-secondary" %>
        <%= link_to "Delete", product, class: "btn btn-danger", method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure ?" } %>
        <%= link_to "Edit", edit_product_path(product), class: "btn btn-warning", data: { turbo_frame: "modal" } %>
      </span>

    </div>
  </li>
<% end %>

app/views/products/_product_card.html.erb
<div class="col-lg-4 col-md-6 m-8 p-2">
  <div class="card" style="height: 16rem">
    <div class="card-image">
    </div>
    <div class="card-body d-flex flex-column">
      <a href="" style="text-decoration: none; color: black">
        <h5 class="card-title mb-3"><%= product.name %></h5>
      </a>    
      <h5 class="card-subtitle mb-2 text-muted"><%= product.category.name %></h5>

      <p class="card-text"><%= product.description %></p>
      <div class="mt-auto">
        <%= link_to "Add To Basket", product, data: { turbo_frame: "_top" }, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/products/create.turbo_stream.erb
<%= turbo_stream.prepend "products", @product %>

app/views/products/destroy.turbo_stream.erb
<%= turbo_stream.remove @product %>

app/views/products/edit.html.erb
<main class="container">
  <%= turbo_frame_tag "modal" do %>
    <h1 class="display-6 ms-3 mt-2">Edit Product</h1>

    <div class="modal-body">
      <%= render "products/form", product: @product %>
    </div>
  <% end %>
</main>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="row">
  <div class="col">
    <h1 class="display-6">Products</h1>
  </div>
  <div class="col-auto">
    <%= link_to "New Product", new_product_path, class: "btn btn-primary", data: { turbo_frame: "modal" } %>
  </div>
</div>

<ul class="list-group">
  <%= turbo_frame_tag "products" do %>
    <% if @products.blank? %>
      <h1 class="display-6">No Products to list yet...</h1>
    <% end %>
    <%= render @products %>
  <% end %>
</ul>

app/views/products/new.html.erb
<main class="container">
  <%= link_to "Products", products_path %>

  <%= turbo_frame_tag "modal" do %>
    <h1 class="display-5 ms-3 mt-2">New Product</h1>

    <div class="modal-body">
      <%= render "products/form", product: @product %>
    </div>
  <% end %>
</main>

app/views/products/public_index.html.erb
<p style="color: green"><%= notice %></p>

<div class="row">
  <div class="col">
    <h1 class="display-6">Products</h1>
  </div>
</div>

<%= turbo_frame_tag "products" do %>
  <% if @products.blank? %>
    <h1 class="display-6">No Products to list yet...</h1>
  <% end %>
  <div class="row">
    <%= render partial: 'product_card', collection: @products, as: :product %>
  </div>
<% end %>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>

app/views/products/update.turbo_stream.erb
<%= turbo_stream.replace @product do %>
  <%= render @product %>
<% end %>